name=Gemini_AI
version=6.6.0
author=Zahid Arman (zacode123)
maintainer=zacode123
sentence=A simple and highly memory-efficient Gemini AI Client library.
paragraph=An ultra lightweight Gemini AI client library for ESP8266/ESP32.
category=Communication
url=https://github.com/zacode123/Gemini_AI
architectures=esp8266,esp32