name=Gemini_AI
version=5.1.0
author=Zahid Arman
maintainer=Zahid Arman <mofazzolwasimahmed@example.com>
sentence=Library for interacting with the Gemini AI to get answers to questions.
paragraph=This library allows you to easily connect to the Gemini AI from your Arduino device and retrieve answers to questions via WiFi. It supports customizable API tokens and response settings.
category=Communication
url=none
architectures=esp8266, esp32